TST = $(shell cat zdtm-tst-list)
CFLAGS += -D_GNU_SOURCE

.FORCE:

zdtm_ns: $(shell echo "$(TST)" | tr ' ' '\n' | awk '/^ns\// && !/ns\/user/ {print}')
zdtm_ns_user: $(shell echo "$(TST)" | tr ' ' '\n' | awk '/^ns\/user/ {print}')
zdtm_nons: $(shell echo "$(TST)" | tr ' ' '\n' | awk '!/^ns\// {print}')

$(TST): zdtm_ct mount_cgroups .FORCE
	./zdtm.sh --ct ${ZDTM_ARGS} -r $(@) > $(subst /,_,$@).log 2>&1;  \
	{ ret=$$?; fname=$(subst /,_,$@).log; flock Makefile cat $$fname; unlink $$fname; exit $$ret; }

mount_cgroups: .FORCE
	flock zdtm_mount_cgroups ./zdtm_mount_cgroups

zdtm_ct: zdtm_ct.c
