#!/bin/sh

# If a controller is created during dumping processes, criu may fail with error:
# Error (cgroup.c:768): cg: Set 3 is not subset of 2
# so lets create all test controllers before executing tests.

uuid=$1

cat /proc/self/cgroup | grep -q zdtmtst.defaultroot && exit

tdir=`mktemp -d zdtm.XXXXXX`
for i in "zdtmtst" "zdtmtst.defaultroot"; do
	mount -t cgroup -o none,name=$i zdtm $tdir &&
	# a fake group prevents destroying of a controller
	mkdir -p $tdir/holder.$uuid &&
	umount -l $tdir || exit 1
done
rmdir $tdir
