include scripts/utilities.mak
include scripts/feature-tests.mak

CONFIG		:= include/config.h

$(CONFIG): scripts/utilities.mak scripts/feature-tests.mak
	$(E) "  GEN     " $@
	$(Q) @echo '#ifndef __CR_CONFIG_H__' > $@
	$(Q) @echo '#define __CR_CONFIG_H__' >> $@
ifeq ($(call try-cc,$(TCP_REPAIR_TEST),,),y)
	$(Q) @echo '#define CONFIG_HAS_TCP_REPAIR' >> $@
endif
ifeq ($(call try-cc,$(PRLIMIT_TEST),,),y)
	$(Q) @echo '#define CONFIG_HAS_PRLIMIT' >> $@
endif
	$(Q) @echo '#endif /* __CR_CONFIG_H__ */' >> $@

config: $(CONFIG)

.PHONY: config
