#include <linux/filter.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <ptrace.h>

#include "common/config.h"
#include "imgset.h"
#include "kcmp.h"
#include "pstree.h"
#include <compel/ptrace.h>
#include "proc_parse.h"
#include "restorer.h"
#include "sud.h"
#include "servicefd.h"
#include "util.h"
#include "rst-malloc.h"

#include "protobuf.h"
#include "images/sud.pb-c.h"

#undef LOG_PREFIX
#define LOG_PREFIX "sys-dispatch: "

static struct rb_root sud_tid_rb_root = RB_ROOT;
static struct sys_dispatch_entry *sud_tid_entry_root;

/* Autogenerated protobuf message structure */
static SysDispatchEntry *sud_img_entry;

struct sys_dispatch_entry *sud_lookup(pid_t tid_real, bool create, bool mandatory)
{
    struct sys_dispatch_entry *entry = NULL;

    struct rb_node *node = sud_tid_rb_root.rb_node;
    struct rb_node **new = &sud_tid_rb_root.rb_node;
    struct rb_node *parent = NULL;

    while (node) {
        struct sys_dispatch_entry *this = rb_entry(node, struct sys_dispatch_entry, node);

        parent = *new;
        if (tid_real < this->tid_real)
            node = node->rb_left, new = &((*new)->rb_left);
        else if (tid_real > this->tid_real)
            node = node->rb_right, new = &((*new)->rb_right);
        else
            return this;
    }

    if (create) {
        entry = xzalloc(sizeof(*entry));
        if (!entry)
            return NULL;
        rb_init_node(&entry->node);
        entry->tid_real = tid_real;

        entry->next = sud_tid_entry_root, sud_tid_entry_root = entry;
        rb_link_and_balance(&sud_tid_rb_root, &entry->node, parent, new);
    } else {
        if (mandatory)
            pr_err("Can't find entry on tid_real %d\n", tid_real);
    }

    return entry;
}

/* This must run after ptrace freeze but *before* parasite code. */
int sud_collect_entry(pid_t tid_real)
{
    struct sys_dispatch_entry *entry;
    sud_config_t config;

    entry = sud_lookup(tid_real, true, false);
    if (!entry) {
        pr_err("Can't create entry on tid_real %d\n", tid_real);
        return -1;
    }

    if (ptrace_get_sud(tid_real, &config)) {
        pr_err("Failed to get SUD settings for %d\n", tid_real);
        return -1;
    }

    entry->mode = config.mode;
    entry->selector = config.selector;
    entry->offset = config.offset;
    entry->len = config.len;

    return 0;
}
