#ifndef __CR_MPSC_QUEUE_H__
#define __CR_MPSC_QUEUE_H__

/*
 * Type-safe, lock-free Multi-Producer Single-Consumer (MPSC) queue.
 *
 * Uses the classic atomic-exchange-on-tail pattern:
 *   - Producers: xchg(&tail, new) → store(&old->next, new)  (wait-free)
 *   - Consumer:  load(head->next) with ACQUIRE                (same as SPSC)
 *
 * Dummy-node pattern: head always points to a dummy whose ->next is the
 * real first entry (or NULL when the queue is empty).
 *
 * Head, tail and size are passed as lvalues so callers can place them
 * in their own structs with whatever padding they need.
 *
 * NOTE: does not #include xmalloc.h — the including .c file provides it.
 */

/**
 * DECLARE_MPSC_NODE(prefix, entry_type) — generate a wrapper node type.
 *
 *   struct prefix##_mpsc_node {
 *       struct prefix##_mpsc_node *next;
 *       entry_type *entry;
 *   };
 */
#define DECLARE_MPSC_NODE(prefix, entry_type)		\
struct prefix##_mpsc_node {				\
	struct prefix##_mpsc_node *next;		\
	entry_type *entry;				\
}

/**
 * mpsc_init(head, tail, size, node_type) — allocate dummy node.
 *
 * @head, @tail: lvalue pointers of type node_type *.
 * @size:        lvalue unsigned long counter.
 * @node_type:   the struct type generated by DECLARE_MPSC_NODE.
 *
 * Returns 0 on success, -1 if allocation fails.
 */
#define mpsc_init(head, tail, size, node_type)				\
({									\
	node_type *_dummy = xzalloc(sizeof(*_dummy));			\
	int _rc = -1;							\
	if (_dummy) {							\
		_dummy->next  = NULL;					\
		_dummy->entry = NULL;					\
		(head)  = _dummy;					\
		__atomic_store_n(&(tail), _dummy, __ATOMIC_RELEASE);	\
		(size)  = 0;						\
		_rc = 0;						\
	}								\
	_rc;								\
})

/**
 * mpsc_enqueue(tail, size, entry_ptr, node_type) — append an entry.
 *
 * Safe to call from multiple producer threads concurrently.
 *
 * @tail:      lvalue pointer of type node_type *.
 * @size:      lvalue unsigned long counter.
 * @entry_ptr: pointer to the payload entry.
 * @node_type: the struct type generated by DECLARE_MPSC_NODE.
 *
 * Returns 0 on success, -1 if node allocation fails.
 */
#define mpsc_enqueue(tail, size, entry_ptr, node_type)			\
({									\
	node_type *_node = xmalloc(sizeof(*_node));			\
	node_type *_prev;						\
	int _rc = -1;							\
	if (_node) {							\
		_node->entry = (entry_ptr);				\
		_node->next  = NULL;					\
		_prev = __atomic_exchange_n(&(tail), _node,		\
					    __ATOMIC_ACQ_REL);		\
		__atomic_store_n(&_prev->next, _node, __ATOMIC_RELEASE);\
		__atomic_fetch_add(&(size), 1, __ATOMIC_RELAXED);	\
		_rc = 0;						\
	}								\
	_rc;								\
})

/**
 * mpsc_dequeue(head, size) — remove and return the oldest entry.
 *
 * Must be called from a single consumer thread only.
 *
 * @head: lvalue pointer of type node_type *.
 * @size: lvalue unsigned long counter.
 *
 * Evaluates to entry pointer (may be any pointer type) or NULL.
 */
#define mpsc_dequeue(head, size)					\
({									\
	typeof((head)->next)  _head = (head);				\
	typeof(_head)         _next;					\
	typeof((head)->entry) _entry = NULL;				\
	_next = __atomic_load_n(&_head->next, __ATOMIC_ACQUIRE);	\
	if (_next) {							\
		_entry = _next->entry;					\
		_next->entry = NULL;					\
		(head) = _next;						\
		xfree(_head);						\
		__atomic_fetch_sub(&(size), 1, __ATOMIC_RELAXED);	\
	}								\
	_entry;								\
})

/**
 * mpsc_peek(head) — non-consuming emptiness check.
 *
 * Returns true if the queue has at least one entry.
 */
#define mpsc_peek(head)							\
	(__atomic_load_n(&(head)->next, __ATOMIC_ACQUIRE) != NULL)

/**
 * mpsc_size(size) — read the approximate queue size.
 */
#define mpsc_size(size)							\
	__atomic_load_n(&(size), __ATOMIC_RELAXED)

/**
 * mpsc_drain(head, free_entry_fn) — free all nodes and their entries.
 *
 * @head: lvalue pointer of type node_type *.
 * @free_entry_fn: function(entry *) that frees one entry's resources.
 *
 * NOT thread-safe — call only after all producers have stopped.
 */
#define mpsc_drain(head, free_entry_fn)					\
do {									\
	typeof(head) _cur = (head);					\
	while (_cur) {							\
		typeof(_cur) _nxt = _cur->next;				\
		if (_cur->entry)					\
			free_entry_fn(_cur->entry);			\
		xfree(_cur);						\
		_cur = _nxt;						\
	}								\
	(head) = NULL;							\
} while (0)

#endif /* __CR_MPSC_QUEUE_H__ */
