#ifndef __CR_SPSC_QUEUE_H__
#define __CR_SPSC_QUEUE_H__

/*
 * Type-safe, lock-free Single-Producer Single-Consumer (SPSC) queue.
 *
 * Uses the Michael-Scott dummy-node pattern: the head always points
 * to a "dummy" node whose ->next is the real first entry (or NULL
 * when the queue is empty).  On dequeue the old dummy is freed and
 * the consumed node becomes the new dummy.
 *
 * Memory ordering:
 *   Producer publishes via RELEASE store on tail->next.
 *   Consumer reads via ACQUIRE load on head->next.
 *   The size counter uses RELAXED — it is approximate.
 *
 * Head, tail and size are passed as lvalues so callers can place them
 * in their own structs with whatever padding they need.
 *
 * NOTE: does not #include xmalloc.h — the including .c file provides it.
 */

/**
 * DECLARE_SPSC_NODE(prefix, entry_type) — generate a wrapper node type.
 *
 *   struct prefix##_spsc_node {
 *       struct prefix##_spsc_node *next;
 *       entry_type *entry;
 *   };
 */
#define DECLARE_SPSC_NODE(prefix, entry_type)		\
struct prefix##_spsc_node {				\
	struct prefix##_spsc_node *next;		\
	entry_type *entry;				\
}

/**
 * spsc_init(head, tail, size, node_type) — allocate dummy node.
 *
 * @head, @tail: lvalue pointers of type node_type *.
 * @size:        lvalue unsigned long counter.
 * @node_type:   the struct type generated by DECLARE_SPSC_NODE.
 *
 * Returns 0 on success, -1 if allocation fails.
 */
#define spsc_init(head, tail, size, node_type)				\
({									\
	node_type *_dummy = xzalloc(sizeof(*_dummy));			\
	int _rc = -1;							\
	if (_dummy) {							\
		_dummy->next  = NULL;					\
		_dummy->entry = NULL;					\
		(head)  = _dummy;					\
		(tail)  = _dummy;					\
		(size)  = 0;						\
		_rc = 0;						\
	}								\
	_rc;								\
})

/**
 * spsc_enqueue(tail, size, entry_ptr, node_type) — append an entry.
 *
 * @tail:      lvalue pointer of type node_type *.
 * @size:      lvalue unsigned long counter.
 * @entry_ptr: pointer to the payload entry.
 * @node_type: the struct type generated by DECLARE_SPSC_NODE.
 *
 * Returns 0 on success, -1 if node allocation fails.
 */
#define spsc_enqueue(tail, size, entry_ptr, node_type)			\
({									\
	node_type *_node = xmalloc(sizeof(*_node));			\
	int _rc = -1;							\
	if (_node) {							\
		_node->entry = (entry_ptr);				\
		_node->next  = NULL;					\
		__atomic_store_n(&(tail)->next, _node,			\
				 __ATOMIC_RELEASE);			\
		(tail) = _node;						\
		__atomic_fetch_add(&(size), 1, __ATOMIC_RELAXED);	\
		_rc = 0;						\
	}								\
	_rc;								\
})

/**
 * spsc_dequeue(head, size) — remove and return the oldest entry.
 *
 * @head: lvalue pointer of type node_type *.
 * @size: lvalue unsigned long counter.
 *
 * Evaluates to entry pointer (may be any pointer type) or NULL.
 */
#define spsc_dequeue(head, size)					\
({									\
	typeof((head)->next)  _head = (head);				\
	typeof(_head)         _next;					\
	typeof((head)->entry) _entry = NULL;				\
	_next = __atomic_load_n(&_head->next, __ATOMIC_ACQUIRE);	\
	if (_next) {							\
		_entry = _next->entry;					\
		_next->entry = NULL;					\
		(head) = _next;						\
		xfree(_head);						\
		__atomic_fetch_sub(&(size), 1, __ATOMIC_RELAXED);	\
	}								\
	_entry;								\
})

/**
 * spsc_peek(head) — non-consuming emptiness check.
 *
 * Returns true if the queue has at least one entry.
 */
#define spsc_peek(head)							\
	(__atomic_load_n(&(head)->next, __ATOMIC_ACQUIRE) != NULL)

/**
 * spsc_size(size) — read the approximate queue size.
 */
#define spsc_size(size)							\
	__atomic_load_n(&(size), __ATOMIC_RELAXED)

/**
 * spsc_drain(head, free_entry_fn) — free all nodes and their entries.
 *
 * @head: lvalue pointer of type node_type *.
 * @free_entry_fn: function(entry *) that frees one entry's resources.
 *
 * Walks from head to tail, calling free_entry_fn for every non-NULL
 * entry (dummy nodes have entry == NULL) and freeing every node.
 * Sets head to NULL when done.
 */
#define spsc_drain(head, free_entry_fn)					\
do {									\
	typeof(head) _cur = (head);					\
	while (_cur) {							\
		typeof(_cur) _nxt = _cur->next;				\
		if (_cur->entry)					\
			free_entry_fn(_cur->entry);			\
		xfree(_cur);						\
		_cur = _nxt;						\
	}								\
	(head) = NULL;							\
} while (0)

#endif /* __CR_SPSC_QUEUE_H__ */
