#ifndef __CR_SECCOMP_FLAGS_H__
#define __CR_SECCOMP_FLAGS_H__

#include <linux/seccomp.h>

#ifndef SECCOMP_FILTER_FLAG_TSYNC
#define SECCOMP_FILTER_FLAG_TSYNC 1
#endif

#ifndef SECCOMP_FILTER_FLAG_TSYNC_ESRCH
#define SECCOMP_FILTER_FLAG_TSYNC_ESRCH (1UL << 4)
#endif

#ifndef SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV
#define SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV (1UL << 5)
#endif

#define SUPPORTED_SECCOMP_FLAGS (SECCOMP_FILTER_FLAG_TSYNC | SECCOMP_FILTER_FLAG_LOG | \
				 SECCOMP_FILTER_FLAG_SPEC_ALLOW | SECCOMP_FILTER_FLAG_TSYNC_ESRCH | \
				 SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV)

#endif /* __CR_SECCOMP_FLAGS_H__ */
