#ifndef __CR_CONFIG_H__
#define __CR_CONFIG_H__

#define CONFIG_HAS_TCP_REPAIR

#define CONFIG_HAS_STRLCPY

#define CONFIG_HAS_STRLCAT

#define CONFIG_HAS_SETPROCTITLE_INIT

#endif /* __CR_CONFIG_H__ */
