#!/bin/sh
set -x -e

test "$1" = "x86_64" || exit 0

apt-get update -qq
apt-get install -qq protobuf-c-compiler libprotobuf-c0-dev libaio-dev libprotobuf-dev protobuf-compiler python-ipaddr libcap-dev libnl-3-dev
chmod a+x $HOME
make GCOV=1
make -C test/zdtm
python test/zdtm.py run -a -x 'cgroup*'

pip install flake8
make lint
