#ifndef __CR_SHOW_H__
#define __CR_SHOW_H__

extern void show_files(int fd);
extern void show_pagemap(int fd);
extern void show_reg_files(int fd);
extern void show_ns_files(int fd);
extern void show_core(int fd);
extern void show_ids(int fd);
extern void show_mm(int fd);
extern void show_vmas(int fd);
extern void show_pipes(int fd);
extern void show_pipes_data(int fd);
extern void show_fifo(int fd);
extern void show_fifo_data(int fd);
extern void show_pstree(int fd);
extern void show_sigacts(int fd);
extern void show_siginfo(int fd);
extern void show_itimers(int fd);
extern void show_posix_timers(int fd);
extern void show_creds(int fd);
extern void show_fs(int fd);
extern void show_remap_files(int fd);
extern void show_ghost_file(int fd);
extern void show_fown_cont(void *p);
extern void show_eventfds(int fd);
extern void show_tty(int fd);
extern void show_tty_info(int fd);
extern void show_file_locks(int fd);
extern void show_rlimit(int fd);
extern void show_inventory(int fd);
extern void show_raw_image(int fd);
extern void show_eventpoll(int fd);
extern void show_eventpoll_tfd(int fd);
extern void show_signalfd(int fd);
extern void show_inotify(int fd);
extern void show_inotify_wd(int fd);
extern void show_fanotify(int fd);
extern void show_fanotify_mark(int fd);
extern void show_unixsk(int fd);
extern void show_inetsk(int fd);
extern void show_packetsk(int fd);
extern void show_netlinksk(int fd);
extern void show_sk_queues(int fd);
extern void show_utsns(int fd);
extern void show_ipc_var(int fd);
extern void show_ipc_shm(int fd);
extern void show_ipc_msg(int fd);
extern void show_ipc_sem(int fd);
extern void show_tcp_stream(int fd);
extern void show_mountpoints(int fd);
extern void show_netdevices(int fd);
extern void show_stats(int fd);

#endif /* __CR_SHOW_H__ */
