#!/bin/sh
set -x -e

TRAVIS_PKGS="protobuf-c-compiler libprotobuf-c-dev libaio-dev python-future
		libgnutls28-dev libgnutls30 libprotobuf-dev protobuf-compiler
		libcap-dev libnl-3-dev gdb bash python-protobuf python-yaml
		libnet-dev util-linux asciidoctor libnl-route-3-dev
		python-junit.xml python-ipaddress time ccache flake8
		libbsd-dev"

X86_64_PKGS="gcc-multilib"

UNAME_M=`uname -m`

if [ "$UNAME_M" != "x86_64" ]; then
	# For Travis only x86_64 seems to be baremetal. Other
	# architectures are running in unprivileged LXD containers.
	# That seems to block most of CRIU's interfaces.
	SKIP_TRAVIS_TEST=1
fi

travis_prep () {
	[ -n "$SKIP_TRAVIS_PREP" ] && return

	cd ../../

	# This can fail on aarch64 travis
	service apport stop || :

	CC=gcc
	# clang support
	if [ "$CLANG" = "1" ]; then
		TRAVIS_PKGS="$TRAVIS_PKGS clang"
		CC=clang
	fi

	[ -n "$GCOV" ] && {
		apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
		apt-get update -yq
		apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-7
		CC=gcc-7
	}

	# ccache support, only enable for non-GCOV case
	if [ "$CCACHE" = "1" -a -z "$GCOV" ]; then
		# ccache is installed by default, need to set it up
		export CCACHE_DIR=$HOME/.ccache
		[ "$CC" = "clang" ] && export CCACHE_CPP2=yes
		# uncomment the following to get detailed ccache logs
		#export CCACHE_LOGFILE=$HOME/ccache.log
		CC="ccache $CC"
	fi

	# Do not install x86_64 specific packages on other architectures
	if [ "$UNAME_M" = "x86_64" ]; then
		TRAVIS_PKGS="$TRAVIS_PKGS $X86_64_PKGS"
	fi

	apt-get update -qq
	apt-get install -qq --no-install-recommends $TRAVIS_PKGS
	chmod a+x $HOME
}

travis_prep

export GCOV
$CC --version
time make CC="$CC" -j4

./criu/criu -v4 cpuinfo dump || :
./criu/criu -v4 cpuinfo check || :

make lint

# Check that help output fits into 80 columns
WIDTH=$(./criu/criu --help | wc --max-line-length)
if [ "$WIDTH" -gt 80 ]; then
	echo "criu --help output does not obey 80 characters line width!"
	exit 1
fi

[ -n "$SKIP_TRAVIS_TEST" ] && exit 0

ulimit -c unlimited

echo "|`pwd`/test/abrt.sh %P %p %s %e" > /proc/sys/kernel/core_pattern

if [ "${COMPAT_TEST}x" = "yx" ] ; then
	# Dirty hack to keep both ia32 & x86_64 shared libs on a machine:
	# headers are probably not compatible, so apt-get doesn't allow
	# installing both versions, while we need one for CRIU and one
	# for 32-bit tests. A better way would involve launching docker..
	# But it would require making zdtm.py aware of docker and launching
	# tests inside the CT.
	INCOMPATIBLE_LIBS="libaio-dev libcap-dev libnl-3-dev libnl-route-3-dev"
	IA32_PKGS=""
	REFUGE=64-refuge

	mkdir "$REFUGE"
	for i in $INCOMPATIBLE_LIBS ; do
		for j in $(dpkg --listfiles $i | grep '\.so$') ; do
			cp "$j" "$REFUGE/"
		done
		IA32_PKGS="$IA32_PKGS $i:i386"
	done
	apt-get remove $INCOMPATIBLE_LIBS
	apt-get install --no-install-recommends $IA32_PKGS
	mkdir -p /usr/lib/x86_64-linux-gnu/
	mv "$REFUGE"/* /usr/lib/x86_64-linux-gnu/
fi

time make CC="$CC" -j4 -C test/zdtm

[ -f "$CCACHE_LOGFILE" ] && cat $CCACHE_LOGFILE

# umask has to be called before a first criu run, so that .gcda (coverage data)
# files are created with read-write permissions for all.
umask 0000
./criu/criu check
./criu/criu check --all || echo $?
./criu/criu cpuinfo dump
./criu/criu cpuinfo check

export SKIP_PREP=1
# The 3.19 kernel (from Ubuntu 14.04) has a bug. When /proc/PID/pagemap
# is read for a few VMAs in one read call, incorrect data is returned.
# See https://github.com/checkpoint-restore/criu/issues/207
# Kernel 4.4 (from Ubuntu 14.04.5 update) fixes this.
uname -r | grep -q ^3\.19 && export CRIU_PMC_OFF=1

chmod 0777 test/
chmod 0777 test/zdtm/static
chmod 0777 test/zdtm/transition

./test/zdtm.py run -a -p 2 --keep-going $ZDTM_OPTS

KERN_MAJ=`uname -r | cut -d. -f1`
KERN_MIN=`uname -r | cut -d. -f2`
if [ $KERN_MAJ -ge "4" ] && [ $KERN_MIN -ge "18" ]; then
	LAZY_EXCLUDE="-x cmdlinenv00 -x maps007"
else
	LAZY_EXCLUDE="-x maps007 -x fork -x fork2 -x uffd-events -x cgroupns
		      -x socket_listen -x socket_listen6 -x cmdlinenv00
		      -x socket_close_data01 -x file_read -x lazy-thp -x futex"
fi
LAZY_EXCLUDE="$LAZY_EXCLUDE -x maps04"

# Starting with 5.4 kernel requires SYS_CAP_PTRACE to use uffd events; as such
# we cannot run lazy-pages tests in uns
LAZY_FLAVORS=""
if [ $KERN_MAJ -ge "5" ] && [ $KERN_MIN -ge "4" ]; then
    LAZY_FLAVORS = "-f h,ns"
fi

LAZY_TESTS=.*\(maps0\|uffd-events\|lazy-thp\|futex\|fork\).*
LAZY_OPTS="-p 2 -T $LAZY_TESTS $LAZY_EXCLUDE $LAZY_FLAVORS $ZDTM_OPTS"

./test/zdtm.py run $LAZY_OPTS --lazy-pages
./test/zdtm.py run $LAZY_OPTS --remote-lazy-pages
./test/zdtm.py run $LAZY_OPTS --remote-lazy-pages --tls

bash ./test/jenkins/criu-fault.sh
bash ./test/jenkins/criu-fcg.sh
bash ./test/jenkins/criu-inhfd.sh

if [ -z "$SKIP_EXT_DEV_TEST" ]; then
	make -C test/others/mnt-ext-dev/ run
fi
#make -C test/others/exec/ run
make -C test/others/make/ run CC="$CC"
make -C test/others/shell-job/ run
make -C test/others/rpc/ run

./test/zdtm.py run -t zdtm/static/env00 --sibling

./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --dedup
./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --noauto-dedup
./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --page-server
./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --page-server --dedup

./test/zdtm.py run -t zdtm/static/socket-tcp-local --norst

ip net add test
./test/zdtm.py run -t zdtm/static/env00 -f h --join-ns

# RPC testing
./test/zdtm.py run -t zdtm/static/env00 --rpc		# Basic
./test/zdtm.py run -t zdtm/static/env00 --rpc --pre 2 --page-server
./test/zdtm.py run -t zdtm/static/ptrace_sig -f h --rpc # Error handling (crfail test)

./test/zdtm.py run --empty-ns -T zdtm/static/socket-tcp*-local --iter 2

./test/zdtm.py run -t zdtm/static/env00 -k always
./test/crit-recode.py

# libcriu testing
make -C test/others/libcriu run

make -C test/others/shell-job
