name: CI

on: [push, pull_request]

# Cancel any preceding run on the pull request.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/criu-dev' }}

jobs:
  vm-fedora-rawhide-test:
    name: VM Fedora ${{ matrix.name }} based test
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: fedora-stable
            name: Stable
            reboot: true
          - variant: fedora-next
            name: Next
            reboot: true
          - variant: fedora-no-vdso
            name: No VDSO
            reboot: true
          - variant: fedora-non-root
            name: Non-Root
            reboot: false
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/lima-vm-setup
      with:
        template: fedora
        cache-key-prefix: lima-fedora
    - name: Setup VM
      run: lima sudo /home/criu/scripts/ci/lima.sh ${{ matrix.variant }}-setup
    - name: Reboot VM to activate new kernel
      if: matrix.reboot
      run: |
        limactl stop default
        limactl start default
    - name: Show VM info
      run: |
        lima uname -a
        lima cat /proc/cmdline
    - name: Run tests
      run: ssh -tt lima-default sudo -i /home/criu/scripts/ci/lima.sh ${{ matrix.variant }}-test
    - name: Print dmesg
      if: always()
      run: lima sudo dmesg
    - name: Debug via SSH
      if: failure()
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
