name: Cross Compile Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          armv7-stable-cross,
          armv7-testing-cross,
          aarch64-stable-cross,
          aarch64-testing-cross,
          ppc64-stable-cross,
          ppc64-testing-cross,
          mips64el-stable-cross,
          mips64el-testing-cross
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: >
        sudo make -C scripts/ci ${{ matrix.target }}
