name: Cross Compile Tests

on: [push, pull_request]

# Cancel any preceding run on the pull request.
concurrency:
  group: cross-compile-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/criu-dev' }}

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        target: [
          armv7-stable-cross,
          aarch64-stable-cross,
          ppc64-stable-cross,
          mips64el-stable-cross,
        ]
        include:
          - experimental: true
            target: armv7-unstable-cross
          - experimental: true
            target: aarch64-unstable-cross
          - experimental: true
            target: ppc64-unstable-cross
          - experimental: true
            target: mips64el-unstable-cross

    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: >
        sudo make -C scripts/ci ${{ matrix.target }}
