name: Cross Compile Tests

on:
  push:
    branches: [criu-dev]
  pull_request:
    branches: [criu-dev]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mips64el-cross]

    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: >
        sudo make -C scripts/travis ${{ matrix.target }}
