name: Cross Compile Tests

on:
  push:
    branches: [ criu-dev ]
  pull_request:
    branches: [ criu-dev ]
  schedule:
    - cron:  '55 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [armv7-cross, aarch64-cross, ppc64-cross, mips64el-cross]

    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: >
        sudo make -C scripts/travis ${{ matrix.target }}
