name: Daily Cross Compile Tests

on:
  schedule:
    - cron:  '30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mips64el-cross]
        branches: [criu-dev]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branches }}
    - name: Run Cross Compilation Targets
      run: >
        sudo make -C scripts/travis ${{ matrix.target }}
