name: ci

on:
  push:
    tags:
      - v*
    branches:
  pull_request:

jobs:

  alpine:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [GCC, CLANG]
    steps:
    - uses: actions/checkout@v2
    - name: Run Alpine/${{ matrix.compiler }} test
      run: sudo -E make -C scripts/ci ${{ matrix.compiler }}=1 alpine

  centos:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [7, 8]
    steps:
    - uses: actions/checkout@v2
    - name: Run CentOS ${{ matrix.target }} Test
      run: sudo -E make -C scripts/ci centos${{ matrix.target }}

  cross:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [armv7, aarch64, ppc64, mips64el]
    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: sudo make -C scripts/ci ${{ matrix.target }}-cross

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get install -qqy flake8 shellcheck
    - name: Run make lint
      run: make lint

  openj9:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run OpenJ9 test
      run: sudo make -C scripts/ci openj9-test

  podman:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run Podman test
      run: sudo make -C scripts/ci podman-test

  x86_64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [GCC, CLANG]
    steps:
    - uses: actions/checkout@v2
    - name: Run X86_64 ${{ matrix.compiler }} test
      run: sudo make -C scripts/ci ${{ matrix.compiler }}=1 x86_64
