name: ci

on:
  push:
    tags:
      - v*
    branches:
  pull_request:

jobs:

  alpine:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [GCC=1, CLANG=1]
    steps:
    - uses: actions/checkout@v2
    - name: Run Alpine ${{ matrix.compiler }} Test
      run: sudo -E make -C scripts/ci ${{ matrix.compiler }} alpine

  centos:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [centos7, centos8]
    steps:
    - uses: actions/checkout@v2
    - name: Run CentOS ${{ matrix.target }} Test
      run: sudo -E make -C scripts/ci ${{ matrix.target }}

  cross-compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [armv7-cross, aarch64-cross, ppc64-cross, mips64el-cross]
    steps:
    - uses: actions/checkout@v2
    - name: Run Cross Compilation Targets
      run: sudo make -C scripts/ci ${{ matrix.target }}

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get install -qqy flake8 shellcheck
    - name: Run make lint
      run: make lint

  openj9:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run OpenJ9 Test
      run: sudo make -C scripts/ci openj9-test

  podman:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run Podman Test
      run: sudo make -C scripts/ci podman-test

  x86_64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [GCC=1, CLANG=1]
    steps:
    - uses: actions/checkout@v2
    - name: Run X86_64 ${{ matrix.compiler }} Test
      run: sudo make -C scripts/ci ${{ matrix.compiler }} x86_64
