name: X86_64 GCC Test

on: [push, pull_request]

# Cancel any preceding run on the pull request.
concurrency:
  group: gcc-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/criu-dev' }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run X86_64 GCC Test
      run: sudo make -C scripts/ci x86_64
